version: '3'
services:
  app:
    build:
      context: .
    command: bash -c "rails s"
    volumes:
      - .:/webapp
    depends_on:
      - db
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  db:
    restart:
      always
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 43306:3306

volumes:
  db-data:
